export const GET_MATCHING_USERS_REQUEST = 'GET_MATCHING_USERS_REQUEST';
export const GET_MATCHING_USERS_SUCCESS = 'GET_MATCHING_USERS_SUCCESS';
export const GET_MATCHING_USERS_FAILURE = 'GET_MATCHING_USERS_FAILURE';

