export const GET_MATCHING_USERS_REQUEST = 'GET_MATCHING_USERS_REQUEST';
export const GET_MATCHING_USERS_SUCCESS = 'GET_MATCHING_USERS_SUCCESS';
export const GET_MATCHING_USERS_FAILURE = 'GET_MATCHING_USERS_FAILURE';

export const SEND_MATCH_REQUEST_REQUEST = 'SEND_MATCH_REQUEST_REQUEST';
export const SEND_MATCH_REQUEST_SUCCESS = 'SEND_MATCH_REQUEST_SUCCESS';
export const SEND_MATCH_REQUEST_FAILURE = 'SEND_MATCH_REQUEST_FAILURE';

export const ACCEPT_MATCH_REQUEST_REQUEST = 'ACCEPT_MATCH_REQUEST_REQUEST';
export const ACCEPT_MATCH_REQUEST_SUCCESS = 'ACCEPT_MATCH_REQUEST_SUCCESS';
export const ACCEPT_MATCH_REQUEST_FAILURE = 'ACCEPT_MATCH_REQUEST_FAILURE';

export const REJECT_MATCH_REQUEST_REQUEST = 'REJECT_MATCH_REQUEST_REQUEST';
export const REJECT_MATCH_REQUEST_SUCCESS = 'REJECT_MATCH_REQUEST_SUCCESS';
export const REJECT_MATCH_REQUEST_FAILURE = 'REJECT_MATCH_REQUEST_FAILURE';

export const GET_MATCH_REQUESTS_REQUEST = 'GET_MATCH_REQUESTS_REQUEST'; 
export const GET_MATCH_REQUESTS_SUCCESS = 'GET_MATCH_REQUESTS_SUCCESS';
export const GET_MATCH_REQUESTS_FAILURE = 'GET_MATCH_REQUESTS_FAILURE';