export const FETCH_MY_CONCERTS_REQUEST = "FETCH_MY_CONCERTS_REQUEST"
export const FETCH_MY_CONCERTS_SUCCESS = "FETCH_MY_CONCERTS_SUCCESS"
export const FETCH_MY_CONCERTS_FAILURE = "FETCH_MY_CONCERTS_FAILURE"

export const UPDATE_MY_CONCERT_STATUS_REQUEST = "UPDATE_MY_CONCERT_STATUS_REQUEST"
export const UPDATE_MY_CONCERT_STATUS_SUCCESS = "UPDATE_MY_CONCERT_STATUS_SUCCESS"
export const UPDATE_MY_CONCERT_STATUS_FAILURE = "UPDATE_MY_CONCERT_STATUS_FAILURE" 