export const FETCH_MY_CONCERTS_REQUEST = "FETCH_MY_CONCERTS_REQUEST"
export const FETCH_MY_CONCERTS_SUCCESS = "FETCH_MY_CONCERTS_SUCCESS"
export const FETCH_MY_CONCERTS_FAILURE = "FETCH_MY_CONCERTS_FAILURE"

export const DELETE_MY_CONCERTS_REQUEST= "DELETE_MY_CONCERTS_REQUEST"
export const DELETE_MY_CONCERTS_SUCCESS= "DELETE_MY_CONCERTS_SUCCESS"
export const DELETE_MY_CONCERTS_FALIURE= "DELETE_MY_CONCERTS_FALIURE"