export const FETCH_CONCERTS_REQUEST = "FETCH_CONCERTS_REQUEST"
export const FETCH_CONCERTS_SUCCESS= "FETCH_CONCERTS_SUCCESS"
export const FETCH_CONCERTS_FAILURE = "FETCH_CONCERTS_FAILURE"

export const ADD_CONCERTS_GOING_REQUEST = "ADD_CONCERTS_GOING_REQUEST"
export const ADD_CONCERTS_GOING_SUCCESS = "ADD_CONCERTS_GOING_SUCCESS"
export const ADD_CONCERTS_GOING_FAILURE = "ADD_CONCERTS_GOING_FAILURE"

export const ADD_CONCERTS_INTERESTED_REQUEST = "ADD_CONCERTS_INTERESTED_REQUEST"
export const ADD_CONCERTS_INTERESTED_SUCCESS = "ADD_CONCERTS_INTERESTED_SUCCESS"
export const ADD_CONCERTS_INTERESTED_FAILURE = "ADD_CONCERTS_INTERESTED_FAILURE"

export const REMOVE_CONCERT_STATUS_REQUEST = "REMOVE_CONCERT_STATUS_REQUEST"
export const REMOVE_CONCERT_STATUS_SUCCESS = "REMOVE_CONCERT_STATUS_SUCCESS"
export const REMOVE_CONCERT_STATUS_FAILURE = "REMOVE_CONCERT_STATUS_FAILURE"

export const MY_CONCERTS_REQUEST = "MY_CONCERTS_REQUEST"
export const MY_CONCERTS_SUCCESS = "MY_CONCERTS_SUCCESS"
export const MY_CONCERTS_FAILURE = "MY_CONCERTS_FAILURE"