export const GET_ACCEPTED_MATCHES_REQUEST = "GET_ACCEPTED_MATCHES_REQUEST";
export const GET_ACCEPTED_MATCHES_SUCCESS = "GET_ACCEPTED_MATCHES_SUCCESS";
export const GET_ACCEPTED_MATCHES_FAILURE = "GET_ACCEPTED_MATCHES_FAILURE";